language: java
# Enable container-based infrastructure
# see https://docs.travis-ci.com/user/reference/overview/
sudo: false
# Fix 'Expected feature release number in range of 9 to 14' error on xenial and bionic
dist: trusty

jdk:
  - openjdk8

notifications:
  email: false

# Skip the Travis CI's default install command
install: true

script:
- ./mvnw clean verify

